logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
spring:
  datasource:
    url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  jackson:
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  h2:
    console:
      enabled: true
app:
  jwtSecret: afjjjajsidjqowjdklajdihqiwndaskd
  jwtExpirationInMs: 604800000